name: buildx

on:
  ## build Sundays at 4:32AM UTC, in case there are updates to the base image
  schedule:
    - cron: "32 4 * * 0"

  ## build on all pull requests, to verify before merge
  pull_request:

  ## build when release is published (not drafts)
  release:
    types: [published]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
  
    strategy:
      fail-fast: false
      matrix:
        docker-file:
          - path: docker
            tags: "lts"
            platforms: linux/amd64,linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ## prepare outputs for future steps
      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE="${IMAGE_NAME}"
          TEMP="${{ matrix.docker-file.tags }}"
          TAGZ=($TEMP)
          VERSION=${TAGZ[0]}
          for i in "${!TAGZ[@]}"; do
            if [ "$i" -eq "0" ];
            then
              TAGS="${DOCKER_IMAGE}:${TAGZ[$i]}"
            else
              TAGS="${TAGS},${DOCKER_IMAGE}:${TAGZ[$i]}"
            fi
          done
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}

      ## set up QEMU for other architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.7.0
        with:
          install: true

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      ## plain build for pull-requests
      - name: Docker Buildx (build)
        uses: docker/build-push-action@v2.10.0
        if: success() && !contains(github.ref, 'master')
        with:
          push: false
          context: ./${{ matrix.docker-file.path }}
          file: ./${{ matrix.docker-file.path}}/Dockerfile
          platforms: ${{ matrix.docker-file.platforms }}
          tags: ${{ steps.prepare.outputs.tags }}

      ## login for publishing when executing on master
      - name: Docker Login
        if: success() && contains(github.ref, 'master')
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ## build and publish when executing on master
      - name: Docker Buildx (push)
        uses: docker/build-push-action@v2.10.0
        if: success() && contains(github.ref, 'master')
        with:
          push: true
          context: ./${{ matrix.docker-file.path }}
          file: ./${{ matrix.docker-file.path }}/Dockerfile
          platforms: ${{ matrix.docker-file.platforms }}
          tags: ${{ steps.prepare.outputs.tags }}

      ## run inspect when executing on master
      - name: Inspect Image
        if: always() && github.event_name != 'pull_request' && contains(github.ref, 'master')
        run: |
          docker buildx imagetools inspect ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}

      - name: Clear
        if: always() && github.event_name != 'pull_request'
        run: |
          rm -rf ${HOME}/.docker/config.json
